name: Build App 🚀

run-name: Build App 🚀

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build App
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} 🪴
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Prettier 🎨
        run: yarn format


      - name: Run Linter 🧹
        run: yarn lint

      - name: Run build 🏗️
        run: yarn build